fixtures:
  repositories:
     stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
     archive: "git://github.com/camptocamp/puppet-archive.git"
     docker_old: "https://bitbucket.ris.wustl.edu/scm/pup/garethr-docker_old.git"
     wget: "git://github.com/maestrodev/puppet-wget.git"
     apt: https://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    grafana: "#{source_dir}"
